# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference  
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.5

jobs:
  test-script:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          command: export PYTHONPATH="${PYTHONPATH}:/home/circleci/project/git-learn" && pytest --cov .
      - codecov/upload:
          file: /home/circleci/project/git-learn/coverage.xml

workflows:
  version: 2.1
  build-test:
    jobs:
      - test-script
